version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command:  npx cypress run --spec "cypress/e2e/TS1.cy.js, cypress/e2e/TS2.cy.js"
          parallelism: 3
      - cypress/run:
          cypress-command:  npx cypress run --spec "cypress/e2e/TS2.cy.js"
          parallelism: 3    
